### PR TITLE
Roxygen fixes

### LINKED ISSUE #3: Reorganize @import, @importFrom fields
`roxygen2:::parse_blocks()` imports these in a weird format that makes tests hard to write. 

`@import` ought to become a character vector of package names.

`@importFrom` ought to become a list of character vectors. The names of the elements ought to be packages, and the character vectors ought to be names of objects imported from those packages.

### LINKED ISSUE #4: Run pre-exercise code when testing examples
From Devel R Pkgs Ch2 Ex9:

```r
#' @examples
#' data_summary(iris)
#' data_summary(airquality, na.rm = FALSE)
data_summary <- function(x, na.rm = TRUE){
  
  num_data <- select_if(x, .predicate = is.numeric) 
  
  map_df(num_data, .f = numeric_summary, na.rm = na.rm, .id = "ID")
  
}
```

The examples don't run because dplyr and purrr aren't loaded.

I think the easiest fix is to run the pre-exercise code in the student environment/solution environment before running the example code.

So in the PEC, you would write

```r
library(dplyr)
library(purrr)
```

This affects `check_roxy_examples_run()` and `check_roxy_examples_result_equals()`.

### LINKED ISSUE #5: Prevent roxygen2 trying to find the DESCRIPTION file
If the object being parsed has the value `"_PACKAGE"`, then `roxygen2:::parse_blocks()` goes hunting for the DESCRIPTION file, which in this case doesn't exist.

Find some way to turn this behavior off!

### LINKED ISSUE #11: roxygen2:::parse_blocks no longer exists in roxygen2 version 6.1.0
@richierocks a new version of `roxygen2` came out, version 6.1.0, and `parse_blocks` is no longer a hidden function in the package. You use this function in the `R/parse.R` file to find the roxygen blocks. 

As these functions are nowhere used for the moment, I temporarily commented out the tests (in [this branch](https://github.com/datacamp/testwhat.ext/tree/fs-lav-scts)). Feel free to do a PR that makes things work again. I can also do it at some point.

I personally don't think it makes sense to sink time in this until the functions are actually needed.

### LINKED ISSUE #13: Check @import tag in roxygen
Looks like `testwhat.ext` no longer exports `check_roxy_imports_package()` and `check_roxy_imports_object_from_package()`. @richierocks wrote the following SCT a while ago, but it no longer works. 

### Solution
```{r}
#' @import dplyr
#' @import purrr
#' @importFrom tidyr gather
```

### SCT
```{r}
library(testwhat.ext)
ex() %>%
   parse_roxy() %>% {
     check_roxy_imports_package(., "dplyr")
     check_roxy_imports_package(., "purrr")
     check_roxy_imports_object_from_package(., "tidyr", "gather")
  }
```

[GH](https://github.com/datacamp/courses-developing-r-packages/blob/sp-review/chapter2.md#importing-other-packages)
[Teach](https://www.datacamp.com/teach/edit/repositories/761/branches/sp-review)

Was this accidental or is this replaced by some other functions? The plan is to launch the course by EOD, Friday (Aug 24). So any help is much appreciated! 

cc @filipsch

### PR DESCRIPTION
**Pull request by filipsch**
If I am not mistaken, this PR:

Closes #3 
Closes #13 
Closes #5 
Closes #4 
Closes #11 

I have added comments on the issues where you specified a minimal reproducible example. These all work on this branch. 

I am hesitant to invest time into documenting these functions. I suggest you try to understand the source code a bit to see what they do, if things are not 100% clear. It's all pretty cleanly written. I hope you understand.

### CODE REVIEW

**Review by richierocks — APPROVED** [review]
sweet

**Comment by richierocks** [comment]
@filipsch The [use of the `cli` package](https://github.com/datacamp/testwhat.ext/blob/roxygen-fixes/.travis.yml#L5) seems to be causing the build to [fail on travis](https://travis-ci.org/datacamp/testwhat.ext/builds/422046009#L3969). Do we need to worry about this, or should I just go ahead and merge?

**Comment by filipsch** [comment]
@richierocks Yes I'm trying to fix it, but for some reason, `cli` (which is imported by `testthat`) can't be found, even though I have tried installing it explicitly in a multitude of ways. I'm out of ideas...

**Review by sumedh10 — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
