### PR TITLE
Roxygen fix

### PR DESCRIPTION
**Pull request by andy-techen**
I've mainly made two changes to the `roxygen` SCTs:
- Removed the [deprecated and removed](https://roxygen2.r-lib.org/news/index.html?q=registry#extending-roxygen2-7-0-0) `registry` argument in `parse_text()` (used in `extract_roxygen_from_code()`).
- Apparently, `roxygen` no longer allows us to directly index the parsed blocks. I'm guessing this might have something to do with our removal of `registry`. Therefore, I resorted to using the [block functions](https://github.com/r-lib/roxygen2/blob/f4f72748b2519a697c5664257a703cc8435ce4c3/R/block.R) in `roxygen` to extract tags from the state.

Most likely, there's a better way to do this ([tag functions](https://github.com/r-lib/roxygen2/blob/f4f72748b2519a697c5664257a703cc8435ce4c3/R/tag.R) might be something worth digging into). That being said, I've tested out the updated SCTs in Teach and everything seems to be working fine! Please let me know if this seems like a valid solution to you!

### CODE REVIEW

**Review by TimSangster — COMMENTED** [review]
Thanks for keeping us in the loop, sadly I don't know enough R to review fully, will wait for somebody else to review.
Do you have a way to test these changes? i.e. did you locally test it on some code or copy paste it into exercises to check it works correctly? Thank you!

**Comment by andy-techen** [comment]
@TimSangster No worries whatsoever! And yes, I copied the functions into the SCTs and the exercises seem to be passing!

**Comment by andy-techen** [comment]
@richierocks I've added some fixes to the package check functions, as well as the unused equal check functions. The tests in [test-check-roxy.R](https://github.com/datacamp/testwhat.ext/blob/master/tests/testthat/test-check-roxy.R) seem to be passing locally right now! Please let me know if the functions are still failing on your end! Thank you!

**Review by richierocks — APPROVED** [review]

**Comment by richierocks** [comment]
I spotted some tests that were being skipped in the latest testthat. Fixing those meant I found a few cases where the state wasn't being returned from the check function. And there was some gnarly sapply() code I'd written years ago that I swapped out for cleaner purrr code. All looking good now, and test are passing.

@TimSangster Merge at your leisure.

**Pull request merged**
